# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: EPS_OUTCAR
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-toml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      require_serial: true
      args:
        [
          "-rn", # Only display messages
        ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies:
          [
            pytest,
          ]
